### ISSUE TITLE
[libcluster:examplephx] unable to connect to :"examplephx@172.17.0.6"

### ISSUE THREAD

**Issue by manjufy** [bbhoss/k8sexamplephx#1]
Hey,
First of all, thanks for a great Elixir example app with k8. It was very helpful.

I ran into this issue **`[libcluster:examplephx] unable to connect to :"examplephx@172.17.0.6"`**

however application runs well, just keep getting the above warning.

**Comment by bbhoss** [comment]
Does clustering work at all? Does it show it connecting to any other nodes? Please post your kubernetes config and libcluster config.






On Tue, Mar 28, 2017 at 9:21 AM -0600, "Manjunath Reddy" <notifications@github.com> wrote:












Hey,

First of all, thanks for a great Elixir example app with k8. It was very helpful.


I ran into this issue [libcluster:examplephx] unable to connect to :"examplephx@172.17.0.6"


however application runs well, just keep getting the above warning.

**Comment by manjufy** [comment]
Here is my libcluster config

`config :libcluster,
  topologies: [
    examplephx: [
      strategy: Cluster.Strategy.Kubernetes,
      config: [
        kubernetes_selector: "app=examplephx",
        kubernetes_node_basename: "examplephx"]]]`

I'm exactly using your k8s config, not much difference.

```
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: examplephx
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 8080
  selector:
    app: examplephx
    tier: frontend
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: examplephx
    tier: frontend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 3
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   app: guestbook
  #   tier: frontend
  template:
    metadata:
      labels:
        app: examplephx
        tier: frontend
    spec:
      containers:
      - name: examplephx
        image: elixir:v1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PORT
          value: "8080"
        - name: MY_BASENAME
          value: examplephx
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REPLACE_OS_VARS
          value: "true"
        - name: RELEASE_CONFIG_DIR
          value: /beamconfig
        - name: ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: app-config
              key: erlang-cookie
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /beamconfig
      volumes:
      - name: config-volume
        configMap:
          name: vm-config

```
